blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/mendoncart/testes/blob/main/README.md
    about: Check our documentation first
  - name: Discord Community
    url: https://discord.gg/your-server
    about: Discuss your ideas with the community
  - name: Questions & Discussions
    url: https://github.com/mendoncart/testes/discussions
    about: Ask questions, share ideas, and discuss issues
