# Template for feature/enhancement requests
name: Feature Request
description: Suggest an enhancement or new feature
labels: ["enhancement"]
body:
  - type: checkboxes
    id: search-check
    attributes:
      label: Search Check
      description: Please verify you have completed these steps before submitting
      options:
        - label: I have searched existing issues (open and closed) for similar feature requests
          required: true
        - label: I have checked the project documentation to ensure this feature doesn't already exist
          required: true
  
  - type: dropdown
    id: request-scope
    attributes:
      label: Request Scope
      description: What area does this feature/enhancement affect?
      options:
        - Repository Structure
        - Web Portal
        - Character Management
        - Documentation
        - Tools/Scripts
        - User Experience
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Perceived Priority
      description: How important do you think this feature is?
      options:
        - Critical (Blocks usage)
        - High (Major improvement)
        - Medium (Nice to have)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? Please be specific.
      placeholder: "When I try to..., I want to be able to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "The system could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples?

---
# Template for category/tag requests
name: New Category or Tag Request
description: Request new categories or tags for content classification
labels: ["category", "enhancement"]
body:
  - type: checkboxes
    id: search-check
    attributes:
      label: Search Check
      description: Please verify you have completed these steps before submitting
      options:
        - label: I have searched existing categories and tags in categories.json
          required: true
        - label: I have searched existing issues for similar category/tag requests
          required: true
        - label: I have checked if my request could fit within existing categories
          required: true

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      options:
        - New Category
        - New Tag(s) for Existing Category
        - Both
    validations:
      required: true

  - type: input
    id: category-name
    attributes:
      label: Category Name
      description: For new categories only. Leave blank if requesting new tags.
      placeholder: "e.g., Personality Traits"

  - type: dropdown
    id: existing-category
    attributes:
      label: Existing Category
      description: If adding tags to an existing category, select it here
      options:
        - None (New Category)
        - Rating
        - Species
        - Gender
        - Genre
        - Source
        - Role
        - Personality
        - Fetishes
    validations:
      required: true

  - type: textarea
    id: proposed-tags
    attributes:
      label: Proposed Tags
      description: List the tags you'd like to add, one per line
      placeholder: |
        Tag 1
        Tag 2
        Tag 3
    validations:
      required: true

  - type: dropdown
    id: content-rating
    attributes:
      label: Content Rating
      description: Should these tags be general or NSFW?
      options:
        - General (SFW)
        - NSFW Only
        - Both SFW and NSFW
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Explain why these additions would be useful. Include examples if possible.
      placeholder: |
        - How will this improve content organization?
        - What types of content would use these tags?
        - Why can't existing categories/tags cover this?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example Characters
      description: List some example characters that would use these categories/tags
      placeholder: |
        - Character 1: Would use tags X, Y
        - Character 2: Would use tags Y, Z

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant to your request?

---
# Template config file
blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: ../../docs/
    about: Check our documentation first
  - name: Discord Community
    url: https://discord.gg/your-server
    about: Discuss your ideas with the community
