# Template for reporting illegal/rule-breaking content
name: Report Content
description: Report content that violates rules or laws
labels: ["report"]
body:
  - type: markdown
    attributes:
      value: |
        Please use this form to report inappropriate or illegal content.
  - type: input
    id: content-url
    attributes:
      label: Content Location
      description: Link to the content (folder path or direct link)
      placeholder: "e.g., characters/sfw/character-name"
    validations:
      required: true
  - type: dropdown
    id: violation-type
    attributes:
      label: Type of Violation
      options:
        - Copyright Infringement
        - Illegal Content
        - Against Community Guidelines
        - Other
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide specific details about the violation
    validations:
      required: true
