# .github/workflows/update-categories-template.yml
name: Update Categories in Template

on:
  push:
    paths:
      - 'categories.json'
    branches:
      - develop
      - main

jobs:
  update-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Update Categories
        run: python .github/scripts/update_categories_on_templates.py
      
      - name: Check for Changes
        id: check-changes
        run: |
          git diff --exit-code .github/ISSUE_TEMPLATE/contribution.yaml || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update categories in contribution template"
          title: "Update categories in contribution template"
          body: "Automatically updated categories in the contribution template based on changes to categories.json"
          branch: "auto-update/categories-template"
          delete-branch: true
          base: ${{ github.ref_name }}
