# .github/workflows/update-categories-on-issue-template.yml
name: Update Categories in Templates

on:
  push:
    paths:
      - 'categories.json'
    branches:
      - develop
      - main
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-templates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Update Templates
        run: python .github/scripts/update_categories_on_templates.py
      
      - name: Check for Changes
        id: check-changes
        run: |
          git diff --exit-code .github/ISSUE_TEMPLATE/ || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update categories in issue templates"
          title: "Update categories in issue templates"
          body: |
            Automatically updated categories in the issue templates based on changes to categories.json
            
            Updates include:
            - Contribution template
            - Category request template
          branch: "auto-update/categories-templates"
          delete-branch: true
          base: ${{ github.ref_name }}
